### ISSUE TITLE
Will a new version be published without the coffeescript dependency?

### ISSUE THREAD

**Issue by chasemaier** [SimonSimCity/meteor-job-collection#1]
I see that the most recent commit (https://github.com/SimonSimCity/meteor-job-collection/commit/f8817876f05c37cd4fba82fe83b56007154f7063) removes the CoffeeScript dependency.

Was curious if you plan to release a new version to atmosphere that includes this change?

**Comment by SimonSimCity** [comment]
I don't see a reason to release a version for this alone since it's a major change in the code structure which I also want to have covered by tests.

As of now, I don't have time to work on the further optimization of the code and would love if others step in and continue the work I've started by understandable incremental steps (each a commit) and push their work in here as a pull request. If we have a stable version which also is rewritten into modern javascript, I'd be very glad to release a new version.

But there will definitively come a time where I'll mostly focus on separating the two packages (`job-collection` and `job`) to have a clear separation between running and orchestrating the jobs.

Maybe I can even go for a standalone installation which you could run on any system having `nodejs` installed and access to the db ... and a manager, which you can supervise ... the current system is vulnerable in this regard (see how much issues there are about zombie-jobs ... https://github.com/vsivsi/meteor-job-collection/search?q=zombie&type=Issues)
